import FactorialRatio.ExternalTheorems

/-!
# Fixed-slope algebraic independence

This file records the exact value-level boundary of the formalization. The analytic
Salikhov, Salikhov--Viskina, Levelt--Turrittin, trace-descent, and Beukers arguments
are supplied through `FixedSlopeAlgebraicIndependenceInput`. Lean verifies the
algebraic consequences of that input and exposes the extension from rational to
real algebraic coefficients.
-/

namespace FactorialRatio

/-- The fixed-slope basis is algebraically independent over `ℚ`, conditional on
the explicit analytic input. -/
theorem fixedSlopeBasis_algebraicIndependent
    (published : FixedSlopeAlgebraicIndependenceInput) (a : ℕ) (ha : 1 ≤ a) :
    AlgebraicIndependent ℚ (fixedSlopeBasis a) :=
  published.independent a ha

/-- Algebraic independence persists after extending the coefficient field from
`ℚ` to the subfield of real numbers algebraic over `ℚ`. This is the real-valued
form of independence over `Q̄` used by the manuscript. -/
theorem fixedSlopeBasis_algebraicIndependent_realAlgebraic
    (published : FixedSlopeAlgebraicIndependenceInput) (a : ℕ) (ha : 1 ≤ a) :
    AlgebraicIndependent (Subalgebra.algebraicClosure ℚ ℝ) (fixedSlopeBasis a) :=
  (published.independent a ha).subalgebraAlgebraicClosure

/-- Every member of the fixed-slope basis is individually transcendental. -/
theorem fixedSlopeBasis_transcendental
    (published : FixedSlopeAlgebraicIndependenceInput) (a : ℕ) (ha : 1 ≤ a)
    (i : Fin (a + 1)) :
    Transcendental ℚ (fixedSlopeBasis a i) :=
  (published.independent a ha).transcendental i

/-- Evaluation identifies the polynomial algebra on `a + 1` variables with the
algebra generated by the fixed-slope basis. This packages the statement that the
basis has no polynomial relations. -/
noncomputable def fixedSlopePolynomialEquiv
    (published : FixedSlopeAlgebraicIndependenceInput) (a : ℕ) (ha : 1 ≤ a) :
    MvPolynomial (Fin (a + 1)) ℚ ≃ₐ[ℚ]
      Algebra.adjoin ℚ (Set.range (fixedSlopeBasis a)) :=
  (published.independent a ha).aevalEquiv

end FactorialRatio
